In [1]:
import numpy as np

In [3]:
n = int(input('Введите число: '))
data = np.diag(np.arange(n-1, -1, -1))

print(data)

Введите число: 6
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


In [4]:
np.trace(data)

15