In [4]:
import numpy as np

In [9]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [ 4, 12, -3 ] )

print(a, '\n\n', b)

[[4 2 1]
 [1 3 0]
 [0 5 4]] 

 [ 4 12 -3]


In [10]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [11]:
#проверка
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True